<div class="row bloc">
    <a href="" > Ajouter un article</a>
    <table>
        <thead>
        <tr>
            <th>Référence</th>
            <th>Nom</th>
            <th>Prix d'achat</th>
            <th>Prix de vente</th>
            <th>Fournisseur</th>
            <th colspan='3'>Actions</th>
        </tr>
        </thead>
        <?php
        foreach ($art as $article) {
            echo '<tr><td>' . $article->getRefArt() . '</td>'
            . '<td>' . $article->getNomArt() . '</td>'
            . '<td>' . $article->getPrixaArt() . ' €</td>'
            . '<td>' . $article->getPrixvArt() . ' €</td>'
            . '<td>' . $article->getFournArt()->getNomFourn() . '</td>'
            . '<td><a href="">Modifier</a></td>'
            . '<td><a href="">Desactiver</a></td><'
            . 'td><a href="">Supprimer</a></td></tr>';
        }
        ?>
    </table>
</div>

