<?php
if($id>20){
    $main = " - Femmes";
}elseif($id>10){
    $main = " - Enfants";
}
?><div class="row bloc">


<h1><?php echo $cat -> getNomCat(); ?><span><?php echo $main; ?></span></h1>
<div class="aff">

<?php 
if($articles){
    foreach ($articles as $article) {
        ?> <section> <?php
        echo '<img src="http://placehold.it/300/666666/ffffff" alt="img">';
        echo '<a href="#">'.$article -> getNomArt().'</a>';
        ?> </section> <?php
    }
}
?><p>&nbsp;</p>
</div></div>

