
<div class="row">

    <div class="col-md-8">
        <h1>Présentation</h1>
         <div class="news">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales malesuada leo 
            vel suscipit. Aliquam rhoncus justo suscipit, eleifend ligula quis, posuere nisl. 
            Suspendisse facilisis non dui at fermentum. Maecenas et ex non neque placerat cursus 
            ut eget felis. Quisque enim sem, dapibus eu egestas quis, pulvinar non ante. Sed sit
            amet mattis est. Vivamus sagittis bibendum erat, sit amet fringilla ex. Aenean finibus
            ipsum justo, et blandit eros molestie quis. Nam id nisl nec felis sollicitudin ornare 
            et tempus lacus. Nulla pharetra eleifend vehicula. Nam a hendrerit purus. In lobortis 
            pharetra nibh, ut ultrices diam tempor sed. Etiam ultrices id est luctus luctus. Cum 
            sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
            Quisque iaculis nisl nec sem consequat suscipit.
            Praesent at sem nisi. Phasellus tempus elit quis tempor porta. Duis nec sem tincidunt, gravida lectus viverra, volutpat turpis. Suspendisse luctus nibh vel turpis tristique congue. Aenean molestie sapien eu tempor interdum. Vivamus fermentum nunc non ante commodo hendrerit. Quisque et mi pellentesque, ullamcorper dui ac, imperdiet lectus. Donec ex nunc, mattis eu nisi eget, accumsan luctus quam.
            Donec non elit blandit, ultrices nisl sed, aliquet erat. Proin vitae aliquet lectus. 
            Etiam rhoncus purus nunc, non egestas nibh cursus sit amet. Nulla tristique diam diam,
            at ultrices orci pellentesque non. Cras eu pretium dui. Aliquam lobortis pellentesque
            posuere. Donec pulvinar, justo sit amet aliquet imperdiet, dolor orci porta lorem, 
            nec bibendum sem enim eu libero. Integer scelerisque blandit lobortis. Vivamus 
            ultrices elit lacus.</p>
    </div></div>

    <div class="col-md-4">
        <h1>Nouveautés</h1>
         <div class="news">
        <img class="center-block col-md-6" src="http://placehold.it/120/666666/ffffff" alt="img">
        <img class="center-block col-md-6" src="http://placehold.it/120/666666/ffffff" alt="img">
        <img class="center-block col-md-6" src="http://placehold.it/120/666666/ffffff" alt="img">
        <img class="center-block col-md-6" src="http://placehold.it/120/666666/ffffff" alt="img">
         <img class="center-block col-md-6" src="http://placehold.it/120/666666/ffffff" alt="img">
        <img class="center-block col-md-6" src="http://placehold.it/120/666666/ffffff" alt="img">
        <span>Voir plus</span>
         </div>
    </div>


</div>
