
<?php
if(!$_SESSION){
  $form = $this->form;
      $form->prepare();
    $form->setAttribute('action', $this->url('connect'));
    echo $this->form()->openTag($form);

?>
<table>
    <tfoot>
        <tr>
            <td>
<?php echo $this->formSubmit($form->get('submit')); ?>
            </td>
            <td>
                 <a href="/creation">S'inscrire</a>
            </td>
        </tr>
    </tfoot>
    <tbody>
    
    <tr>
        <th><?php echo $this->formLabel($form->get('email')); ?>
        </th>
        <td>
            <p>
<?php echo $this->formInput($form->get('email')); ?>

            </p>    
<?php echo $this->formElementErrors($form->get('email'), array('class' => 'error_list')); ?>
        </td>

    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('password')); ?></th>
        <td>
            <p>
<?php echo $this->formInput($form->get('password')); ?>

            </p>
<?php echo $this->formElementErrors($form->get('password'), array('class' => 'error_list')); ?>
        </td>

    </tr>
    

</tbody>
</table>
<?php
echo $this->form()->closeTag(); }

else {
    echo "<section>";
    echo "Bonjour ".$_SESSION['nom']." ".$_SESSION['prenom']."<br>";
    echo "Mon Panier :<br>";
    echo '<a href="/connect">Se déconnecter</a>';
    echo "</section>";
}
?>                   