<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>

        <header>
            <img src="/../img/ban.jpg" alt="Zend Framework 2"/>

        </header>
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded" role="navigation">

            </div>  

           
               <a href="<?php echo $this->url('home') ?>">Accueil</a>
                <div class="dropdown">
                <a class="dropbtn">Enfants</a>
                <div class="dropdown-content">
                    <a href="/cat/11">Pantalons</a>
                    <a href="/cat/12">Hauts</a>
                    <a href="/cat/13">Robes</a>
                    <a href="/cat/14">Vestes</a>
                    <a href="/cat/15">Chaussures</a>
                    <a href="/cat/16">Accessoires</a>
                </div>
            </div>
                <div class="dropdown">
                <a class="dropbtn">Femmes</a>
                <div class="dropdown-content">
                    <a href="/cat/21">Pantalons</a>
                    <a href="/cat/22">Hauts</a>
                    <a href="/cat/23">Robes</a>
                    <a href="/cat/24">Vestes</a>
                    <a href="/cat/25">Chaussures</a>
                    <a href="/cat/26">Accessoires</a>
                </div>
            </div>  
                <a href="">Bric à Brac</a>
               <a href="">Contact</a>

          
            <!--/.nav-collapse -->

        </nav>
        <div class="container">
        <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2017 - <?php echo date('Y') ?> by Bruno Marty. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
