<?php echo $this->doctype(); 
error_reporting(0);

?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('La Recycle')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <div id="user">
            <?php
       
            ?>
        </div>
        <header>
            <img src = "/../img/ban1.jpg" alt = "Zend Framework 2"/>

        </header>
        <nav class = "navbar navbar-toggleable-md navbar-light bg-faded" role = "navigation">

     


        <a href = "<?php echo $this->url('home') ?>">Accueil</a>
        <div class = "dropdown">
            <a class = "dropbtn">Enfants</a>
            <div class = "dropdown-content">
                <a href = "/cat/11">Pantalons</a>
                <a href = "/cat/12">Hauts</a>
                <a href = "/cat/13">Robes</a>
                <a href = "/cat/14">Vestes</a>
                <a href = "/cat/15">Chaussures</a>
                <a href = "/cat/16">Accessoires</a>
                <a href = "/cat/17">Bébé 0-18 mois</a>
                <a href = "/cat/18">Puériculture</a>
            </div>
        </div>
        <div class = "dropdown">
            <a class = "dropbtn">Femmes</a>
            <div class = "dropdown-content">
                <a href = "/cat/21">Pantalons</a>
                <a href = "/cat/22">Hauts</a>
                <a href = "/cat/23">Robes</a>
                <a href = "/cat/24">Vestes</a>
                <a href = "/cat/25">Chaussures</a>
                <a href = "/cat/26">Accessoires</a>
            </div>
        </div>
        <a href = "/cat/3">Bric à Brac</a>
        <a href = "/contact">Contact</a>


        <!--/.nav-collapse -->

    </nav>
    <div class = "container">
        <?php echo $this->content;
        ?>
        <hr>
       
    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
            <script>
            $(document).ready(function () {
                $.ajax({
                    url: "/log",
                    dataType: 'json',
                    complete: function (event) {

                        event = event.responseText;
                        console.log(event.length);
                        $('#user').append(event);


                    }
                });
            });
        </script>
</body>
</html>
